
plugins {
    id 'java'
}

jar {
    manifest {
        attributes(
            'Main-Class': 'src.main.java.main.Main'
        )
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.hamcrest:hamcrest-core:1.3'
}

test {
    testLogging {
        showStandardStreams = true
    }
    useJUnit()
}
